---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  63656239646364396539623131396632336265306638653331643264393464646364663930343939
  3464376162646333303534343332636534626636313965620a383466316339663832323734623838
  36373337646362343262643832303839373336323037343130376233356565333461373637623662
  3230393564636330650a383938336539326532373339363232646263343164336438346331353134
  35316133343366313634653130393362633663643935306362393435633236656363366333656434
  3638393231393065393264633663353631313337396364656439
proxmox_haproxy_cookie_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  66323233663537633132343961343365323830316465323334313939643131653236376234363038
  3437303238626438623830306562383664623534343236360a316261393635356230313034616365
  31636430313530323633656339373863633035326630646363626435663064383534663036336364
  3234626432323035300a333561356534616233376135616366653237636635336635313266333539
  31343839333863386630666134303132353966313264656261313333663031366434376162323137
  3862343466666536333861633164363736323934313531646539
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  36386265613662633362303562333831643462623565383766383736386261656239323736626366
  6139356432633734376164633765386530616565373039340a313433386564653936343535303033
  38353863663131376233393339616335353032373833653331373137636161646163643938313666
  6161633062666231310a376535613736393032653434346566653830343034313064326334303531
  3330
