---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  61363531633835353666313063656633373335303333653361396632353837653431646539613531
  6166313134353132373632633734353236623838633434300a623162313365373331633064613566
  62303564383032653135623862656338633233633031643838376438306334643761316330303139
  3264633631363037360a343163373237663364343464343237363264313739386237383165626236
  39643835623734636638313365313332336434656132383735343237313735623763636363373033
  6463346561313764326534633762636432313534303065353333
