---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  64303365393334666562646265376438626463333835613438326434633331653136326139343939
  3763633131386562313432653666363237666264336565340a346564613063633536623965303131
  64316561323230636334353234623337363666393531373932356239393134316164653762656631
  3230663263653861650a353464636639633763303135363932663833323465333539366531646534
  63313366346661383439393437316536366166663363306136616337336535623737
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39313235376264353439396138363763353537333565333337316161346461373563383538613661
  3738393061666231383839383266386232613363356566310a343632643238306162333763666431
  36653331633039313864316263356465336133373466373132653737393966623238636666326333
  6164626333323238630a316230303264373366373564396461323331393861353136303730663665
  64376161353665383463303737613866626232666139323730376230633032373565373539656233
  3038383130653065393061636531663564346661303935633939
