---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  63373636343833373839646264666237343735343061613139336235363465343339343130366363
  6539633938643335666437316462363566626334303738330a363830363762643230616137353833
  65643438373436306230663934656165643034383134663836383334666532366639626663376138
  3466383565383835610a336366346661636135613039656366306365323033346661323065336138
  30656239373663303131666538313932306635633730393035363561306262663030313964663764
  3064393333303162373663343232353839636231653839393766
rabbitmq_erlang_cookie: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62643936323433616662393338316538646366333062373636646336333763643064633664623964
  3563393562363732386136386663643832646433326361620a323763383863643964313064653133
  61356139313166383966336131393830636533613362396434383063656436613363383366623461
  3932343336616666360a333562386465373761626532633565663032633433653066303432616462
  66356564363535336131356431323565386139636436653936633532613937643565333339323935
  3232373030343065633630613231356631353339373464623663
rabbitmq_admin_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  61626538656233343361396435386330303264663834393236363366313536333239613962303738
  3131653063626634333465633366313965356561356561350a373933326466626533346535393736
  38333630316462626466326538313138653730396331373830373863623939343164386562333966
  3866313037613136630a373362333538373961386162323366353662363830376265306234303532
  3266
