---
cephclient_mounts:
  - user: "mediamanager"
    fs_name: "Media_EC"
    remote_path: "/"
    mount_path: "/mnt/Media"
cert:
  - mediamanager.server.home.brwyatt.net
certbot_certs:
  - "{{ cert }}"
reverseproxy_sites:
  - server_names: "{{ cert }}"
    destination: "http://127.0.0.1:8000"
