---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  65643132656465656232376231366465383136326463323833643266646165643934646665646461
  3936653266643434346239366139316334613631636464650a353332343066306262653966333035
  36323238333065396534653435376438633136303136343931643662323935613866373031373831
  3239613232656461650a376265383230393266383537326266333264316363666532396635656331
  37616163393535626463396432633139313432393032653737653938646164353634
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62376536663164336230303039383331303766393435356338323638653631356662393164343738
  3035336136303933383333386232303433353036323734390a316439353037383063306330353231
  35323937333963646133393532383837306332323666623365666535386238633463343864323961
  6137383732363134300a643635633461633836383134633333643132616563396662663733356230
  61616137303962653032373231386362333336663362323030356166346166336632643031643833
  3561373234643833623564393734353963663235653463316632
cephclient_users:
  mediamanager: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    61326166303964303665656533396563376431623530373638643831323438376239393137363538
    6133326230633666313633353364623866633538323465320a333832356635373063343961386639
    38393139613462366539663530633239313836643738326362333263656531393639303138303163
    6234656134353136660a386166633162623933373565383465633665643962373062306235646166
    64343733616561383730343433393238303566343066666436613364633738646138343663656536
    3930323661373637386566336339373464306434666430653234
