---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39613034626238313331303262383335393136333961303937656666656538396366663135656461
  6464623262643566363439626530343761343735353065380a333230373339633038323431303735
  36656335616461653732633238306434303939653136326364373761383631656638653937643663
  6334393365363664640a353037623839373937353163393233376465313436376433613166346639
  38383261363636356631336164376265376661316364353865646164313436356539373231366564
  3531323963646337373764396561366337633266626136613165
cephclient_users:
  mediamanager: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    61326166303964303665656533396563376431623530373638643831323438376239393137363538
    6133326230633666313633353364623866633538323465320a333832356635373063343961386639
    38393139613462366539663530633239313836643738326362333263656531393639303138303163
    6234656134353136660a386166633162623933373565383465633665643962373062306235646166
    64343733616561383730343433393238303566343066666436613364633738646138343663656536
    3930323661373637386566336339373464306434666430653234
