---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  32653332346230393366333862633633336335646234666135346338623439656466646136306331
  6464363435306237363030386337303536363964373339640a643966303532393936346234613264
  37653339303138343762383234303737386238653131326131376630613564303362656234363665
  3962333732636635390a393933623830303639316464383735363966333837623132363537303337
  35313664633265393834376234633663616338373330626338393333633531343032
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  63303833353238383533333132643135633434396339313837643165653437633336366161646637
  3731353863363562376362623639663135333663663533350a663832663234646563643836653437
  62386363333633666362363432303934653331313165386565373533643862376462396238393230
  6361356166653466630a333661386436393238373536633135643163363032303864383439393365
  65323961303565623961323261336534363730323537313537656439376533316162326433336262
  6338346230363639613661393461353130663563613231643931
cephclient_users:
  sonarr: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    63613639626233386465356562363937633764646238623435333236333062663835373735633464
    3362636239616338373734393533313536306339343932310a366362373836396538646365326431
    63626134633839643164356262366537616236643061393635333935616436323361613633633863
    6664336564636533330a623034396662383433643134613730353831356564366439333066356630
    66316434626536653333616132303563383463346362333637653366376235343133353537323133
    6136353766333066646235336566386662336466663638633734
