---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39383634656536666164306435333430643933653836623132376531323333306338316263656135
  3237626430343765386562313534366335383061663234660a396336343561653864383238336437
  62396139626435376638323339353230633464666132336336623331393864613134623964366666
  6562336334306163660a376536383564353236316264343261623339653765343063333366613065
  31383632663339376136643538326461656231663664656564646534646565383736663533663931
  3466653863333038633561376563613437376564386238333866
cephclient_users:
  sonarr: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    63613639626233386465356562363937633764646238623435333236333062663835373735633464
    3362636239616338373734393533313536306339343932310a366362373836396538646365326431
    63626134633839643164356262366537616236643061393635333935616436323361613633633863
    6664336564636533330a623034396662383433643134613730353831356564366439333066356630
    66316434626536653333616132303563383463346362333637653366376235343133353537323133
    6136353766333066646235336566386662336466663638633734
