---
- name: Restart MariaDB
  when: not (bootstrap_result.changed | default(false))
  ansible.builtin.service:
    name: "{{ mariadb_service }}"
    state: restarted
- name: Reload Xinetd
  ansible.builtin.service:
    name: xinetd
    state: reloaded
