---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  38643064366564386539306631313539383939353730636262326238306561333262326532363730
  3862346465343731646565303264333333363663396137380a386565336436613064383639383734
  36396239623532323138636465386565616433656561326563343934653934646435353132623962
  6238356632636331360a643232333861386466376565323736333937386162386534313033363164
  39303834646531656336623237636233346633646430396137303263653361303831633331396537
  3135633937616438633464326130653764633235396533626165
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39663930643033653832333631333766316264643264393138626538356665613364626130636139
  3337663335633234373431653139343530376236306465300a653263333635646264396630633038
  63656163386366666163636163623833316339313831393930376233653836613533373138366632
  6362636461653635630a303035393063616435613832663265363635386336343937306165343030
  3739
sspasswd_keyphrase: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  31653934653332656534613537653132623065323763306466663066633137626163653234386535
  6637376561613561363233613638623434346236663837390a316639343536353865336163316537
  65653133613162343335366637363236646539613139393439393966626539636636626336373465
  3830323861613761620a636161646134383562663932313264333231393337313139313731323836
  3864
sspasswd_ldap_bindpw: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33663162343035636238393664623136393462346666323365653934663931306630303835313730
  3632656333656363386230383035353037323465306333330a636231623362613736356161346662
  32363938303731636366623461343832343139323034376637316531306636356631336437613763
  3939663564613164610a366565336164333139366635313637343730393761396162356539386262
  66386339383530353264353237653763366536616232623739616132656463626661
