aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33373063323536646135636637623136323339323630316235623262383538306363373131353566
  3139306566333838363938616637333430306230616365310a633632646232653833346534363231
  33653462356465313832666665636332363934616131363763613735376636653438346433303533
  3335343832303861330a613165306664353562353162633438393638353631306636336233376131
  63306462396566623039323862666332333237633566326162363861326561396533306564653065
  3561316266313662663539343064343265396163636563363030
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  64303039343165633131623461633861663961663535356637626465303136346332336332343665
  3466333164396263623137363161643561363363666534310a393736313539323433306565373836
  39633231633765633164646537626634343438323031666135666665613735636139656262643834
  6666313031353065350a353262303961356531313462316633373562346239623863336639653236
  3238
