---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  61333432323934376661656539643332303035393337663631633363376135343334343261636630
  3132356461303837303730623161366530393963393930620a323130313932613037386139613563
  34373536323935383631356162333339393739623639313566323034356535613939306466333031
  3532353036613934630a376137666238313463616238636566383037333562376661396239383438
  37623961386663636339633566623765393866396539643031303233323031323765623933663966
  6534626264306634356164333763346665383238376363343030
cephclient_users:
  radarr: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    35343566656561383561616263313035303139656330666632623536303933356531313761646534
    6531393536313430616634316439613639653062323331350a633635393861636635633736313466
    65323632316534373032663032353937356538313232613366343031623730346539613639393261
    3839623931336432660a636263366638653333363534636537666338333165323639623835333834
    32393339616533393139393538333330363065313534633036393562353433313435386166343664
    6366623335666538323432393337366434373265326430636262
