---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62363738306362363265353332386434303032623464383061373430326435393861306136313265
  6661623431346139383163346639633237326564373939370a636233393666393131626664376338
  37666131616431356232306237303634383532616362663765646262653331303061306536376434
  3136643963393364650a643931376637393331613138316333643030376439356362343135626230
  36616464353035326130356232396635666538396531393563666531316232383035
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  66393865393739343362366465366462303362666334613464326335393033353263326463666338
  6339646336643637306365363861333963373639666335310a633339323138323461653963366662
  39663065323638656437636563326562393933643930363166326131653462643866326661316137
  3265343362336461610a306461306434326531346161653462343833386430313536633432383630
  36363162616263633135353365316666366662313063663838303333633165643531366332343361
  6232613930313935366465633063663638313265303533323663
cephclient_users:
  radarr: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    35343566656561383561616263313035303139656330666632623536303933356531313761646534
    6531393536313430616634316439613639653062323331350a633635393861636635633736313466
    65323632316534373032663032353937356538313232613366343031623730346539613639393261
    3839623931336432660a636263366638653333363534636537666338333165323639623835333834
    32393339616533393139393538333330363065313534633036393562353433313435386166343664
    6366623335666538323432393337366434373265326430636262
