---
cephclient_users:
  iscsi: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    63343938366636393434386237333561363366643862346333316137643465653034656530356264
    3338623862396561316336663937303439383166656164610a303132616465613536363930393235
    31323065363935333635366566323232363065366165623031353331353333623435616231353166
    3132353635393562390a333964373766343132323164333334396437636332646432356236303132
    39363138613338626361666237653531636235613838346431633033653135336162626664373631
    3033383633626139306331333363316633303961346538653533
