---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39373036653238356461303436336665616362396238666365636637383564336130356231656364
  3932623133386165353739313033663863323531396662340a613138373161656437316232666164
  61356363353131616265633233393639383633623339303966303038643065386563306338303966
  3235626531313234610a393334613263636563393034613530333461326363666532353237393535
  30323236643935643163386639356137663664626335376438383639386662373633313232323061
  3862316132356163333166346366336136356332383063363461
wsrep_cluster_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  30353233343562363737306364396265643435376231626138613664306539333865363137643637
  6462303632333533643162353733613234656466633064380a653134333337653264393535356137
  37623761643635646635326530383733643131633561633237623035636230323862306166653565
  6464353565613965340a336330653037643636363337346364363639653266386264313634313236
  64376163653861326165643664346432366331383336383462633030626437333430
mysql_root_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  36356462303333663032656664636231323564666162633230313134313134663263356562616664
  6533663138356431633631643738326564333265363833640a303537313663313731663935313739
  61383135613466376266396630383734383461383564353838353363396131373336326661343832
  3732323330353935630a396637623739313535393766373133653433623532626338303262633038
  63623464303662346232366138393361353362623736306537303066613631626339
mysql_clustercheck_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33343062343237353630663465663365613262326336303263316338323830303063353130636465
  6538383166303236356538306630366435313235353437620a303833366335346637316535663839
  32623331313230383535306562653732333236316362323738393532643137383638316563613935
  3766346538653838640a666462383839653362323737313565336433383530333866316133653462
  36396437363962643432633061366636646636666531316461613164633732323431
