---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  38623733396235383631663262303039366465373364343164343636363932353830393062323365
  3134383037383231663937373034636432633037383934350a626539363830333233613331646333
  38336132666431306231653738343863383638666436366565623163356434636465626561623831
  3637306461373734650a386238353034643465633732323461633031356464303463656332373465
  37306639373561363863396161303530623334393431313634323435336230343938
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35383030336166613764653932613039613138363433386538383234306535373735343138653833
  6566363230343833653034656663316236303564656636320a613337373966343635653736653861
  37663764623332346333616366373966663562653464653633643966346637373838663065623530
  6165303438306665640a643130353065343361383536376137373365373933336432313136653539
  39316335613735653264366635363933396464366632306666393635336232653733643664323437
  3434316439313837316333376538356533623237646337336131
