---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39313830653831343462306261346464633630373037666566313935353766376136656639663764
  3432653831333735396262616136653736383931393066650a656430373639613037656230353964
  65666463666137386462303462373037346639646536353434396531656539653061663630633833
  6563313461666132630a316265366635356437363537333861333161323338363538363237373132
  32393765306339313263333661646539306138656130323136613336353438636135326537313235
  3633306463343538616534383638393634333564343939396165
