---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62396137616230383765303237623761613864346134393636343762336664636561396137303733
  3336306663623566623065353637623930303232633031630a323866663631383234326532393062
  33656631336137336334333930643764373831623337313563653538393263656436636639613963
  6530623030613739650a373561386466636437383939366635333561663864306564303163646235
  38353962396365343235373435396366373130663531356235663434626237333735313463353762
  3762356664353238303233396132633966653535643865663964
proxmox_haproxy_cookie_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33633631656165613836666435303233666265316261626132356462396565613961353264646138
  3466653431346531303432323933326339383830616537320a643766343165633263636431646566
  61363064316133633933626237346233373563323630616662613563653736303534396439323865
  3563343138336636630a636239653731636338343436313730653532356338363334323239633330
  38653336343036643766323237343330306163623163616338666331613332306261386232663438
  6364386533383930323465633065343639616263393133663462
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62353436363365336164396338636565653134356130626662666234306463333265623039653438
  6431393630323631393432613838353165663761323339610a313065633032383432643436323264
  31653063393565633132336632646130363863353665323262633030343435353439326336643438
  6565363337663264370a646465663738323762626261346166323932366437353631333634383430
  3062
