---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39636466633661353465633634666466323762326135353136363061346563626537356335666431
  3138333631633430326166363131333232623335316562350a366163383334313435663663373561
  35616262393266313661616332646465353165326231363466346237663065636234643264633537
  3533383030633137360a323565383862383330666231316635343330376166663637353837303561
  64343835383133396231323033636361663861323637333830623234393066346561323538633636
  3134306535323864383438313064326435653937313664653637
