---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33633635633639633933366132336634663465316330343438376163663731626564303861633130
  6439336630666465616162336633383563346638623163640a393138666537343934383739323937
  62363632323734633232626230623437373463343330323735366133343264663838636538396438
  3734393863616539640a386437636137616131323338306434636633303738613733666661363033
  62376463393861363430646634356464343761633633316138363734646464323561
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  66656334343539303738326130653666653836323831326661656430616131353939663066663837
  3535633266316131383232393662343334656235666136650a313132316664396230653462613564
  30386532323361393163373361646663386538633135333931633938643239303531663962366331
  3966363732313134340a646464633237633835626131656264613737323938663738643735336531
  37636164303939666164333032316338373138643761633261386331646231616333376431356137
  3038633564616663393132346438643064636631653363366631
