---
cephclient_mon_dns_srv_name:
  domain: "home.brwyatt.net"
cephclient_mounts:
  - user: "jellyfin-server"
    fs_name: "Media"
    remote_path: "/JellyfinCache"
    mount_path: "/mnt/jellyfin"
  - user: "jellyfin-server"
    fs_name: "Media"
    remote_path: "/JellyfinHome"
    mount_path: "/var/lib/jellyfin"
    mode: '0750'
  - user: "jellyfin-server"
    fs_name: "Media"
    mode: '0700'
    remote_path: "/Media"
    mount_path: "/mnt/media_original"
bindfs_mounts:
  - source_path: "/mnt/media_original"
    mount_path: "/mnt/media"
    mode: '0700'
    map:
      - "root/jellyfin"
      - "@root/@media"
