---
cephclient_mounts:
  - user: "jellyfin-server"
    fs_name: "Media_EC"
    remote_path: "/JellyfinCache"
    mount_path: "/mnt/jellyfin"
  - user: "jellyfin-server"
    fs_name: "Media_EC"
    remote_path: "/JellyfinHome"
    mount_path: "/var/lib/jellyfin"
    mode: '0750'
  - user: "jellyfin-server"
    fs_name: "Media_EC"
    remote_path: "/"
    mount_path: "/mnt/media_original"
bindfs_mounts:
  - source_path: "/mnt/media_original/Media"
    mount_path: "/mnt/media"
    map:
      - "root/jellyfin"
      - "@root/@media"
