---
cephclient_users:
  jellyfin-server: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    36656531653638363638633835323464316466353733633066623933366564653332373761343262
    3030323563656539653833316532396134306537363362360a323935323139356131353865373030
    64323464396339333161626136353762396639316162303333643363353939373039633730323136
    3363333131323938650a636465326164616335333462343363333165353233336436386539653638
    62653130616539396566323165303635386564383331336339373032316631396465393730346366
    6131323231626161356563333566393437313239353132373235
dffmpeg_hmac_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39316237346661653938336662613862346236373062336131613039653032393330313465383033
  3634333136336533633738313633306466396231316232630a653731613464396662636463633463
  65653432333064333932346136653938663737393730393663363930313638383331363936373635
  3531313739393161380a643731386532646461326630333033393163643732616564626538636335
  31396165643636343061383935336664386361663736326331326632376530356264396537656139
  3539323233303864393433356532663762636231393737613165
dffmpeg_rabbitmq_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33386162643539353531616532313037396261366263316235313663636330636537363538643330
  3263376331343362633461333162343936303061663631340a333461316238366432663939663963
  36353636336530656166343934643531393938636666623266323432356536366461323961366335
  3765396137623137620a633064353065376165663234333664346161623362663038633466616164
  65323262633866666333656332626166636234633039396633366166396233616566
