---
cephclient_automount: false
cephclient_mounts:
  - user: "jellyfin-render"
    fs_name: "Media_EC"
    remote_path: "/JellyfinHome"
    mount_path: "/var/lib/jellyfin"
    mode: '0750'
  - user: "jellyfin-render"
    fs_name: "Media_EC"
    remote_path: "/"
    mount_path: "/mnt/media_original"
bindfs_automount: false
bindfs_mounts:
  - source_path: "/mnt/media_original/Media"
    mount_path: "/mnt/media"
    map:
      - "root/jellyfin"
      - "@root/@jellyfin"
