---
cephclient_automount: false
dffmpeg_enable_worker: true
dffmpeg_user: jellyfin
dffmpeg_group: jellyfin
dffmpeg_hmac_key: "{{ dffmpeg_hmac_keys[dffmpeg_client_id]}}"
dffmpeg_rabbitmq_user: "dffmpeg-{{ dffmpeg_client_id }}"
dffmpeg_rabbitmq_password: "{{ dffmpeg_rabbitmq_passwords[inventory_hostname_short] }}"
dffmpeg_paths:
  JellyfinCache: "/mnt/jellyfin/cache"
  JellyfinMetadata: "/mnt/jellyfin/metadata"
  JellyfinHome: "/var/lib/jellyfin"
  Media: "/mnt/media"
dffmpeg_mounts:
  - path: "/mnt/jellyfin"
  - path: "/var/lib/jellyfin"
  - path: "/mnt/media_original"
  - path: "/mnt/media"
    dependencies:
      - "/mnt/media_original"
dffmpeg_mounts_sudo: true
cephclient_mounts:
  - user: "jellyfin-render"
    fs_name: "Media_EC"
    remote_path: "/JellyfinHome"
    mount_path: "/var/lib/jellyfin"
    mode: '0750'
  - user: "jellyfin-render"
    fs_name: "Media_EC"
    remote_path: "/"
    mount_path: "/mnt/media_original"
bindfs_automount: false
bindfs_mounts:
  - source_path: "/mnt/media_original/Media"
    mount_path: "/mnt/media"
    map:
      - "root/jellyfin"
      - "@root/@jellyfin"
