---
cephclient_users:
  jellyfin-render: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    34316636613430646537663335646331613234356366633831363666396238303436336164656338
    3931653036616365336366643034646464643438303638350a663735633661353330666530333261
    31333032343563646130396665316332343365316237663434646266666566363832393266303036
    3734653838316539300a653433336464663966396432313062663131373637343833323937343861
    39616461383961343364626630313164333562613933663962366433306332356263376162336163
    3631323363636638323530333365663766356463363161656337
dffmpeg_hmac_keys:
  render01: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    66396562333933313134613966336665623032313639386239366636373738346137656532333732
    6630653261393135333163633165366238303565366565320a386265356563383036393562353364
    65326562346237393064643630663930663132363065643835306239663536323565643535636233
    3064633037333066330a343562633363396262623637366664656632353363623561376337633863
    61376664636662306535303432333134373065356631623234626235343764636366373333623731
    3731336437333562303931333263373536373239323637336161
  render02: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    62623266353539633838333334613537336164326565653764303565663236363239353665646261
    3037353065643863393466333939346565363566656532310a626431336264333832623564333637
    61636566643836363135393365336337386532396236343363653461303166313634356139613462
    3735363339616537380a303965326138343565346565623130373136646665356465636264396662
    38323838633631396666313735643630323436383063613764633436363838316139353436613865
    3332653339346162663765303437326461383636636431633562
  render03: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    34616530316438393637356338353431396363346664393430386161643864373934623434663433
    3666343063393837383830313239613165323764616235620a653038303933316262363033333262
    37616639663864366262656663343737646132373631656666366566323165383337336337636362
    3135383839383665330a393034616364633965623963653561633265326134663336666564616435
    62643734633533376265373134313162396230303966346364643535333534623263376665636134
    6332343032353663623530343436326363623365393136653962
  render04: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    32623734633261373165393934336238373164363438353430643032343361306338353364353962
    3365613034366236303565323766653937326664356137620a356534623862343030366432613934
    37616632303565616534333438393235306631353735363066626237373038346661626139333030
    6635656538326331370a313162323936383439656161653536376335333532663636613861316661
    33313361363566653238623730306130653835336662626335363330653365656661306561386661
    3966386565393663323637373436666162636138323239326133
dffmpeg_rabbitmq_passwords:
  render01: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    31393665323362653338323632386264336436343036343432646138396231346334626362623161
    6665616336386461336437633030393631373862353931620a313431393761313764333235616632
    36656238363638346562326430383964643337323531643564666166396566646464366338646337
    6633616236373561660a313839633138343733656535356336396433653630663936393937623566
    38323132313434616438663462663335393833333639326138653537356436633635
  render02: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    39346438616266313165396330383938663139653964323038366434663231643461383333303638
    3263666432383532643165346538363834653634643662360a303438373836373163623532393235
    34373532376633626537393165393137613066333935663234356139316334366639363933646166
    6364313737666661320a366261626435343136313965663535373937343063316530326230623331
    35313436613336623938623136346630373338643536623730646132633664623266
  render03: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    31343365663463373130333335393731636534646334663236626330373630393661616233643863
    3738373031633235313665346162663765616332363438310a633135623733346132386232656433
    35613362306130616337663939646437626364386361313737333664313362623435636638333936
    6335333066343665340a353962336534373031373964386232383563653931643138343830626333
    64616265366636623333386665646461656533666436386135303363326137353335
  render04: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    32613639633032633830343661336365616133613231333466396530366433653566383331316161
    3730643732333330356165383431623031353939636339370a303131376533316534353364663530
    32343861373861366636326464643631313365393732636261613836366231346334306131343635
    3332383061333333350a353336656631313739613236333030623061663766363030643132646161
    65353737613064616132333334303966383166643164313538313363353463633465
