---
- name: Restart DFFmpeg Coordinator
  ansible.builtin.service:
    name: dffmpeg-coordinator
    state: restarted
    daemon_reload: true
  become: true
- name: Restart DFFmpeg Worker
  ansible.builtin.service:
    name: dffmpeg-worker
    state: restarted
    daemon_reload: true
  become: true
