---
- name: Create Coordinator directory
  ansible.builtin.file:
    path: "{{ dffmpeg_base_dir }}/coordinator"
    state: directory
    owner: "{{ dffmpeg_user }}"
    group: "{{ dffmpeg_group }}"
    mode: '0750'
  become: true
- name: Create Coordinator venv and install package
  ansible.builtin.pip:
    name:
      - "git+{{ dffmpeg_repo_url }}@{{ dffmpeg_version }}#subdirectory=packages/{{ dffmpeg_common_package }}"
      - "git+{{ dffmpeg_repo_url }}@{{ dffmpeg_version }}#subdirectory=packages/{{ dffmpeg_coordinator_package }}"
    state: latest
    virtualenv: "{{ dffmpeg_base_dir }}/coordinator"
    virtualenv_command: python3 -m venv
  become: true
- name: Deploy Coordinator configuration
  ansible.builtin.template:
    src: coordinator.yaml.j2
    dest: "{{ dffmpeg_base_dir }}/coordinator/dffmpeg-coordinator.yaml"
    owner: "{{ dffmpeg_user }}"
    group: "{{ dffmpeg_group }}"
    mode: '0640'
  become: true
  notify: Restart DFFmpeg Coordinator
- name: Deploy Coordinator encryption keys file
  ansible.builtin.template:
    src: keys.yaml.j2
    dest: "{{ dffmpeg_auth_encryption_keys_file }}"
    owner: "{{ dffmpeg_user }}"
    group: "{{ dffmpeg_group }}"
    mode: '0600'
  become: true
  when: dffmpeg_auth_encryption_keys is defined
  notify: Restart DFFmpeg Coordinator
- name: Deploy Coordinator systemd service
  ansible.builtin.template:
    src: dffmpeg-coordinator.service.j2
    dest: /etc/systemd/system/dffmpeg-coordinator.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart DFFmpeg Coordinator
- name: Ensure Coordinator is started and enabled
  ansible.builtin.service:
    name: dffmpeg-coordinator
    state: started
    enabled: true
  become: true
