---
- name: Create Worker directory
  ansible.builtin.file:
    path: "{{ dffmpeg_base_dir }}/worker"
    state: directory
    owner: "{{ dffmpeg_user }}"
    group: "{{ dffmpeg_group }}"
    mode: '0750'
  become: true
- name: Create Worker venv and install package
  ansible.builtin.pip:
    name:
      - "git+{{ dffmpeg_repo_url }}@{{ dffmpeg_version }}#subdirectory=packages/{{ dffmpeg_common_package }}"
      - "git+{{ dffmpeg_repo_url }}@{{ dffmpeg_version }}#subdirectory=packages/{{ dffmpeg_worker_package }}"
    virtualenv: "{{ dffmpeg_base_dir }}/worker"
    virtualenv_command: python3 -m venv
  become: true
- name: Deploy Worker configuration
  ansible.builtin.template:
    src: worker.yaml.j2
    dest: "{{ dffmpeg_base_dir }}/worker/dffmpeg-worker.yaml"
    owner: "{{ dffmpeg_user }}"
    group: "{{ dffmpeg_group }}"
    mode: '0640'
  become: true
  notify: Restart DFFmpeg Worker
- name: Deploy Worker systemd service
  ansible.builtin.template:
    src: dffmpeg-worker.service.j2
    dest: /etc/systemd/system/dffmpeg-worker.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart DFFmpeg Worker
- name: Deploy sudoers rule for DFFmpeg mounts
  ansible.builtin.template:
    src: dffmpeg-sudoers.j2
    dest: /etc/sudoers.d/dffmpeg
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: true
- name: Ensure Worker is started and enabled
  ansible.builtin.service:
    name: dffmpeg-worker
    state: started
    enabled: true
  become: true
