aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35363731663161336463343836633134326561626537313131623363666233373064313034326665
  6465303165383066343633366662373536623766346238650a663234366237396334616633316434
  34393633636433643361393264313361303138343539613564363335376430643265643731623638
  6530323737383731620a663235303632663331303739333239383961373531323836336162303534
  32323230613863623231316139333162663239303561626534376663653032623932653832656436
  3238366562313032616639303139356239633533306637326364
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  65366332363432353864313733363934623763636630616561363239383237336362393337633837
  6633373430313830323761383139636538646434353636640a333337343435643166373533663035
  39363365666662643261326530343161396361636135653236616463316533353463653365623732
  3735643733613765390a656138613461623965663438373532386661323932656134333738326339
  3838
