---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33346336643332643265393333313232323731326462393932636261316161643539386436653030
  3231613362313064333730613531313035336438396236620a306263383032336136353266313361
  37383631376337353330376532346634363832613136336662613562643039313838333766643961
  6637316439636564380a356136343137303835323133616665616666336465326534303165343464
  39613836316239646464353865306330346337326361316665326536663433333138346434313930
  6238303836666564323939383166396233306231326232303237
mqtt_haproxy_cookie_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  65383235383439323663333130383132326366663361313532653935636662366239353564636239
  3966666364303338623235393933663139383735363464610a643232333232646466373632303663
  64663238303463613662666433663361383034383462313237663461346262346263663166643538
  6565386538663133630a383762646632396538666665663639353365366166353366303131336435
  64363430313164353036643731383636613366613832336330363262383061663861363734633935
  6339653466623839636532323638333334336366376665376665
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  63316236313337383763366434323931653631366135356364643139306138343964393463336561
  3731386165306162346131643032643331633862393532630a303364626136383931633566363431
  38383333303661376462383333393434343130373635633666396662303365613330393366653134
  3463316333326265630a373032656238346633383433366434656431396364643036616138343338
  6262
