---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  33303836363666333134653239303163333235383764323239666236366632656665393163623532
  6566613933643061383534663035363663343532363934610a346333303036646238336539393333
  66646436393863353736376136323131336437653663326262663132366131666131613638353331
  6565643338366335340a383534623862326430373961373936353836366633346333383035666137
  39663936333630393663663339623033663335363435353264623431313162646336653431386238
  6137373763306163363535343737376132396162393462663561
