---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  38336537666635613037366362646631383233626462373237636231353461613331343937623265
  3562343762313335333438356462363430616438613361380a623938353963306136353266326366
  36306635306537303265303861376138353336313031356665363061353864343934653566373438
  6631326465663563610a386237376630666633636536356564653330376431653764313038346630
  64386364366437326539383235336338356332633433623765303365376231623138643337343238
  3635633836666562323661643037343964353633316165643665n
