---
dffmpeg_enable_coordinator: true
dffmpeg_mysql_user: dffmpegcoordinator
dffmpeg_rabbitmq_user: dffmpeg-coordinator
dffmpeg_coordinator_listen_address: "127.0.0.1"
dffmpeg_auth_default_encryption_key_id: "20260215"
dffmpeg_trusted_proxies:
  - "127.0.0.0/8"
  - "172.17.30.89/32"
  - "172.17.30.134/32"
  - "172.17.30.208/32"

proxy_port: 8000
