aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62336632333338323933633930353538623237633636303533613636326662376338623536626435
  3130613137383263373636306637396163393537353832370a346234313761383936643237636438
  37303037303764616232663037623238353666393239636538663134313230353139376462326161
  3432666238343238370a633239353735333265333036633334343134636234373931393231353330
  61623432653839336136633337376434643866653964616239386363343161656233656135336337
  66376132356531636137633734343532623931373664313061373463616663616266326162626263
  336363316331383436613035633065623039
dffmpeg_mysql_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  37623462666639653462633438306333316539633761616537353162306531336231326230363262
  3932313337326237643637346131616366343361303135610a303236343430333732623465636133
  33613966333532643764623430306139316165386133613333346133653536313039616638623338
  6565333961346561310a646638393732663430313339666235656638363633663766643166663265
  36623735333733663063633239353930663463333437373864643235666632363338
dffmpeg_rabbitmq_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35346532316636366637333265653563386564633738653731316637643862373538623465666561
  3466313063663866316266353332313465646562633063340a303264653661333461326432626639
  65383733656163613364646438653734373136393266613830666666306134373864356665343931
  3638386262336237650a393034646565336661306438373339346433313866336538353239336430
  64396262663163646435666630323437356132643830373566666238393439326664
encryption_keys:
  "20260215": !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    30343366306433633664313561313837353561383035666334373465343534336564633330323566
    3265373737366337343735343663646539366362376130380a626432303861613130666231666162
    39363135323232393839336634613837653633356438613738636232656236653832626361343234
    6561323238616133620a333332636532396536376236356436306137623463326533663238396232
    63366436326163366335363533313264623438353963636630303266623566356561323265316663
    62336463306530383537326233323133653363663939393566336336343231633131386435343837
    373862326330363331303863313963636434
