---
certbot_certs: "{{ acmecertpusher_certs.values() }}"
acmecertpusher_hosts:
  skylightkvm.kvm.home.brwyatt.net:
    method: ssh
    ssh_hostkey: "ssh-rsa 12345abcd"
    ssh_user: root
    cert: skylightkvm
    key_dest: "/etc/kvmd/user/ssl/server.key"
    cert_dest: "/etc/kvmd/user/ssl/server.crt"
    commands:
      - "/etc/init.d/S99kvmd-nginx restart"
acmecertpusher_certs:
  skylightkvm:
    - skylightkvm.kvm.home.brwyatt.net
