---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35393364383137373762326632383431393832303133626463373236656538343163316239316263
  6661613130393938613030396433356232663834333763320a343930333337316536383064626463
  36373932346365633636373263346166646266316165666231333531653261323762396563366637
  3765666465623764340a353138323866303639396431343235313436646534343963383839366338
  32373563393262316334343163636238326462393062316265326262303932323937366239663730
  6130653861376364396263613330363834636663386638656136
acmecertpusher_ssh_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39333231626165346365653036613361373237333139306130633637356261333739386165386633
  3337636331373263613635653466376363363436653638360a336230613866623234666164646634
  31393733643264356366653034356231373739356432346232616632643731626533643035366336
  6534336635623838300a643938656236643434396330393835393239386530636362626565613539
  62346236643762366135326134636163653832643963663433363864393964323965393836353838
  62663434376662366463336461383838313032653934663363656661643230343430363565616439
  34633133363861626639323066323066326661643766353163646465326362643736653736376631
  65363962353864653766313664663837333935616461333561616535303138633333653330636262
  61613161643630663263646131366430313437346635633234376264343832663634636437323333
  61616266313262303736323465353432373530363266613331313238333739353864633262333230
  63353232646661633035663234636132383062343434353832653763333261313432373538373863
  38663362363163326531663532653230616135633333383363336438646265646631343336303664
  62616163643631643861396364633536346162393136653133356239643963643633366561653464
  63383663376435373766653034636637666631663536323739666233653238343339383731356666
  64333439623335363031303538353234653739643437386665356638313263346138623364376664
  64396566663632303538373162316132663234396465613135376166313930313531616439666236
  35393537626662633938363231313839333964653764656664383262396262363533646362316637
  38316439376439313035633432663066393034353766623634393930353138356436356331343733
  63666135353138373539656131343239323530313731373932656632373230306330386432613937
  36366463383435613036313334353666616339366432643935346365376131313165656535396637
  35663164386236393966366531313335363734653537616133303362663332303832303436343163
  38376336396165623961663732626261353836316133653439643261613336323230623635396332
  33636432653865313336616261326136666431653665613433613565356661343738346537393833
  65663837636263316434393439393962393362343662313563376239616239666131663431383661
  65323638326565343833643135333366326361396663373632386533623963336232
