---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35393364383137373762326632383431393832303133626463373236656538343163316239316263
  6661613130393938613030396433356232663834333763320a343930333337316536383064626463
  36373932346365633636373263346166646266316165666231333531653261323762396563366637
  3765666465623764340a353138323866303639396431343235313436646534343963383839366338
  32373563393262316334343163636238326462393062316265326262303932323937366239663730
  6130653861376364396263613330363834636663386638656136
acmecertpusher_ssh_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  64306134643636323736663835343937626361373333623830663864373531343633653962323062
  3637313738366562316366323433643134366431376636370a303861353164303037633335393939
  30343232306461346566313066383563613465646363376363336564656133666232373930663963
  6237393233343631380a386236643336323666386235393562616263396261623261656336383565
  35353063353135323131653334323763393530616331303134343435616633646566666137653466
  61646162303466396566383339363332666338333338643564323537323633386332346461613763
  34653264353066373235353363366631383835326638343431643932356136616536656430386437
  30633133376366353562386666363132636661363432373066363033353464313366653232386466
  38633666343565643138346266333130643938333139396463353535333833643063303934613964
  31333132356462656130336639636166366331623235393165393362306134623165626161396538
  31663665346334616535326138343334316532313134336331653164303036323539386332303165
  30313136303166396365306265373539633264316139343630373035646338376339323235313161
  35643336613165663361303633666638653438383330373735333364363631353663666131356661
  65306333353730653331326531376462643964656532663938326135626665386636303935306465
  33356139616366333263313564393032303363303264313630316437616630376361393538353161
  31626230346136323230383063333634353131633135613330663966343733646265663631326465
  62326439313261373464366630326232356362613965346136616265653237313363376462353333
  65343637386235353731613331303764623332303763333935623664343830646231323264363733
  36366338643032356437313037333636636561373562396134383438363230643364356130333634
  61363130303530366235633762623137656565333565343864633061626637653662653734613234
  64633236643936333132653464663633316235653038636137393837353938653931373933663262
  34383733636461613335326562323133396637643331356636323966626639393435616465396566
  36646564336666656564623362353339336561313763333866616334376339376434616166323766
  32363835356662653638623961353637333465383966626534393464346536363966626137393366
  65383962373231313064326664303037663139363365393231663838303563663934303563633264
  33333961626363663063613332363530373365373366363936383864386531393265613761343834
  65333566633531316465623734633662346565613533343465366335353733626636303862306566
  33623866636139353132643832363533653233343131336361303363643336333739343235343866
  61383636333138623861656165336363643064613864656538623732363931336232303862356466
  33653962656535636130336532376364383633656166626134386362353065656631346137353033
  326234346539383930346364613965653830
