---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35393364383137373762326632383431393832303133626463373236656538343163316239316263
  6661613130393938613030396433356232663834333763320a343930333337316536383064626463
  36373932346365633636373263346166646266316165666231333531653261323762396563366637
  3765666465623764340a353138323866303639396431343235313436646534343963383839366338
  32373563393262316334343163636238326462393062316265326262303932323937366239663730
  6130653861376364396263613330363834636663386638656136
acmecertpusher_ssh_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  37353362366134636639333864376131616536623466376463636530336635303763343437613938
  3633653061623530643335316162323062646635336333650a383834303435613666366566326532
  36626631616533383263633835323137613032356239653061633664383939623266373633623965
  6661343236396561380a646162376663333535363937393466383238376139323363326636666139
  32373766343861333330313533376366303437343132366134383861343464303865316161363762
  34646565333036303430313634363464666435366339386666626632643936316233663366306132
  30626366636264326136376337313761666535616139666231343430616666343530303239336639
  39306662306136623939633836383734393738303232356361373030326537316535353633666465
  62616466613764623263653434663234383735386232376533346635303065393661366461613437
  30323530336563633931386461643839613665623230366337663164386231383035313237313633
  63663434643464623362653666643139613363316136633165376631306364363338366535333766
  30643061643233333166333539623239383131333533316563636262633933333963343839333331
  33616637636138333938336164333337373264636334313839313263366161303637323131313463
  62313037656261666139626635643539353030326463396130356266326530373939343832353835
  36663135623862393666353932323834373163366130353037663034323230313230366235636331
  32623863653130653936363665323134376338616533323434323331346336666535373631626636
  39623932316533376262343961613863656431623738663963333236353465643564313063616566
  31376262333864643466396130386464636563363835343562643161646339353738353235366362
  64316332643761353036306338306465353261356261656332343265333838383736613465623763
  39653030366163373734346165313139346538663139313961396261383164363661336333306438
  66396361366133316335666335666465626534343231303866633132616664613166386531623233
  62643039343763653135636666393462356535366265386437303663313931343036303665386332
  38333666303535636531633264383639333561363932333031303030643030326232616433376264
  30343764316362393035666631613737303861386366346263313333653465656436306334653763
  63306338383362346631333261623039336337643135623233663430303232653333303038353934
  36306263613133366335373432363433353161653866633538353636393162623237383666616537
  626436616132626264336538303063373338
