---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  35393364383137373762326632383431393832303133626463373236656538343163316239316263
  6661613130393938613030396433356232663834333763320a343930333337316536383064626463
  36373932346365633636373263346166646266316165666231333531653261323762396563366637
  3765666465623764340a353138323866303639396431343235313436646534343963383839366338
  32373563393262316334343163636238326462393062316265326262303932323937366239663730
  6130653861376364396263613330363834636663386638656136
skylightkvm_ssh_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  31613163643539323034623364336434316232333935353763373237633664393832383266343439
  3563373065363635653465396635306430666161386631380a656333313264366236333432376664
  34666131363734613264623439613662303730333833353533653732323964636231323563633832
  3439303839316638370a346661663436383566353931626330313635333530383166316565623031
  3863
