---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  62656539613131633466366433386161346139373365393162633464356134646530343338326637
  3538316337326466363562646564666539343637616461390a633366376438616333356630663335
  64303232623666313833616366396433656638643462623434306166323366643063343333363135
  6137353665393765350a313065343861336564333663383338636437343462333937323937323265
  66313839303162346433353365663533643031333830313139333131636132393730
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  66613533393164363163343238613336313662636664323466313738396638306461613265643733
  3932343639316466643861643931353665646533393634380a306462343837396362643262616137
  64356562353466383764346334663635313938623464313136323764613963333834393864626332
  3332396362623738350a616464623437396632393936366137636466663061653733653232626563
  61333637333663636331646639356239303434316239316435363134336361396364663230356237
  6237656639636664323535383733313566313762643833616463
