---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  64623730336135623962376234303533393730393234613966633662373462343064663836316134
  3937353762326664303932373361303536323037306334370a313163386337356234313431363031
  64313964383161396163373561623461636164613462393034663461323536383830393438316636
  3132636137636635390a366164653738373336376130633330653164363438353563373762366464
  39333033653237643861626665396331376237323733666266366332636136353765366137353339
  6236353432393336313532633066373061346239373762616266
