---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  34376666613232633061666366633030306234336434303332616436383733386336616238366632
  3535333863666632353163346262646438666239386662640a663361366531326163323361666633
  35366330643064633164656434643763303637323663646536613865386261633038333831303064
  3662653961323433320a343761306163663264396435656565616363363835643366323861326138
  39326537616232326562663866613233623031333464626537376465343161376438
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  61326337396135643331666531613438373962353335306566636136653139343733633534326130
  3630333934643530356663666563613362303336663833300a613666643032353435323636343935
  39306436316165336431353864313136653535636233313135613664303464386434626466363539
  3537653265623765340a313832303535663231393266656164356330316530366536366237313634
  64346263616331616235316231376532393537306662633731353538306634323830633338343138
  3765613131303432363037376461653634386634396463306234
