---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  38643966363761383136333463663130366562303531393862303432643664633461323464643463
  3832643839326337386537333430343836313664326433310a393334643165373762343461363037
  36323738643133323466333234306139623966363531663836633263646236633834353635363962
  6536386336623531390a666235623061366264643863326631663862346630303963633032316661
  66636665313235366633646337316466353861326633313131376239353362613331363066363135
  6630343164363063636333643630373739663934616338616339
