---
aws_creds_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39353564353931303130376232666566333164336162613461393734386336393938373430306562
  3036313461663930346365666238333334636634653164360a356339343064356432643462643533
  32633039633030363165613966613735666539303065386466386363386530313732363136336534
  3036633064316166340a613062313564643164623962396234616633343538646139313935656334
  66316237313734636263363131376563633131383037376437353963613537386437
aws_creds_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  30393134643934333030353233363064323564353234316561653838613936346362643438333437
  6163666539343931303632303964666333373264323635350a626261326239623930643162636465
  31393661386534396235643335623638646339303938633665326634343764646134666534343565
  6432626661396635610a306635333763626265323834663362333765353639333637613630393030
  31306663386230306564393961366363303362396332633239383937626330396430313038333932
  6132373361363935353361663961336236313432386335343565
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39303265303732656263663839396665633965623733303662363133373733346339306461633933
  3333303132326435303635393634313633316538653037300a643732363534343631396364313233
  32376165383466376264366562653139383738393133393138653965323663393931363438356334
  3133663961663236640a386166363136333263346534333635393862633832383832306664616461
  64373564626465643561633634663132373232636362323062353163626665363163613035346565
  3233393739623730626431356632623333616336316561626433
