---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  39303265303732656263663839396665633965623733303662363133373733346339306461633933
  3333303132326435303635393634313633316538653037300a643732363534343631396364313233
  32376165383466376264366562653139383738393133393138653965323663393931363438356334
  3133663961663236640a386166363136333263346534333635393862633832383832306664616461
  64373564626465643561633634663132373232636362323062353163626665363163613035346565
  3233393739623730626431356632623333616336316561626433
