---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  34663263653237353730353335646330303334313239326536646231393635623231353138323463
  3761633364633566646235656264303034346238313036360a343532643739303533633739343461
  37336238396334636535626230633436323437373465303230363831336165656139333264646233
  3161393964653664370a323633623338303762303236316564643333336239326363376235303430
  31303538316339653962386235393239323232386633653931626136636465343563373032393134
  6236633035643231333863343135366662353032636133323631
ipaweb_haproxy_cookie_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  65333430663065313038393437333032646534623335616232363966626464353737303131333363
  6534386432373962396566333564333038643264356231310a373738353636393866646232336661
  35633232663833633832363135383764346136383961633233396166393062306130656464353437
  6339336336613531640a613537313338393165373532653339346562653462383665653037376234
  63316230643262663964616131666339383139303232333731323637663833316233313833303238
  3934303263336264316436343364396236363166303039663533
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  31613666653638393165646461616166363539636532326162646330376232336565613163643361
  3134383564666562636634323237613763643632646231620a626465333733323661383636303563
  37383632316639656133303863386633663465383961383963353436333435373064356334393838
  3436346565343638330a326533383066333032336235313864306565653433323130323536303161
  3865
