---
cephclient_mon_dns_srv_name:
  domain: "home.brwyatt.net"
cephclient_mounts:
  - user: "seedbox"
    fs_name: "Media_EC"
    remote_path: "/TorrentData"
    mount_path: "/mnt/torrentdata"
  - user: "seedbox"
    fs_name: "Media_EC"
    remote_path: "/TorrentFiles"
    mount_path: "/mnt/torrentfiles"
  - user: "seedbox"
    fs_name: "Media_EC"
    remote_path: "/Media"
    mount_path: "/mnt/media"
  - user: "seedbox"
    fs_name: "Media_EC"
    remote_path: "/Special"
    mount_path: "/mnt/special"
  - user: "seedbox"
    fs_name: "ISOs"
    remote_path: "/template/iso"
    mount_path: "/mnt/iso"
