---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  34393034613537303464343839323936323533333365313064666536653865333331636436393034
  3962346366366261643033633061326264323761386664310a626262393936323436643961626339
  35626165666332316462336431333439643561393963663132316139666632663662613066303135
  3962323433636536330a383233306661313437326462346336346163373834326238616533373065
  31393933393834366365326665626238653764616563323262623433333462383666633931336436
  3830316534623561313336323032343237653833643736343034
cephclient_users:
  seedbox: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    38336336623339376135343162613166343035356466663362336438316166653335313433653762
    6439626638633031336333643461623138363831376336630a653065356561393438383733333536
    61623463663536363862316661343764303134343265633833343538363737666464643437623336
    3133393530646635300a643238646638396630373364363732363835346233663561316135616333
    37383033366134343762333830396638386565323166343533653230376130366564363266303266
    6462613665346635373632383631373862663636343738313766
