---
cephclient_users:
  seedbox: !vault |
    $ANSIBLE_VAULT;1.2;AES256;vault1
    38336336623339376135343162613166343035356466663362336438316166653335313433653762
    6439626638633031336333643461623138363831376336630a653065356561393438383733333536
    61623463663536363862316661343764303134343265633833343538363737666464643437623336
    3133393530646635300a643238646638396630373364363732363835346233663561316135616333
    37383033366134343762333830396638386565323166343533653230376130366564363266303266
    6462613665346635373632383631373862663636343738313766
