---
aws_creds_role_arn: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  31633465343539646464386437636335326666386530363862613365363163373838636431383039
  6566313534613266336237623236306630316533346465310a316362326164353666356164393531
  64656133643062316166393566323633643934356231643231653263343334343366386436363530
  3839613233346139390a393465623865326437343661356564356232336231356234373332613266
  32313036653062373336343934356366343862313839353564363235613234313465653663643363
  63306633376632373339386138343434323836313134613831636639383666633732306330663162
  313131663734373636333635316362613837
rabbitmq_haproxy_cookie_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  30313733666638336162303165396230386566336663613839356436396562666263666134633261
  3662303136383731666439373231333561613038363933300a646266393630613232656536336161
  62326330643864396333393630353439656235613166353663353536623163613532393065366439
  6137373237383764660a626161653163626630326263666439613234646435323735356137393938
  31363834393339643932383735363137333938303930383133393165386362643434653835343565
  3166643232353363356366343339623930653432373239326334
keepalived_auth_pass: !vault |
  $ANSIBLE_VAULT;1.2;AES256;vault1
  34656531373164616463343137323131613930633961363761643832663362333933353334643166
  3331623661633233363366656330366165653731363432650a626436373333366536396636613832
  32626339363264663136353066616365366330656337306636613130323264633163353363666261
  3461663032303437350a333862313665333830346232323430386530656563343636623631653061
  6561
